AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the OrganizationAccountAccessRole for member accounts invited to the Org'

Parameters:

  managementAccountId:
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: OrganizationAccountAccessRole
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
         - Effect: Allow
           Action: sts:AssumeRole
           Principal:
            AWS: !Ref managementAccountId
